### ISSUE TITLE
运行go命令报错/gofrs/uuid@v4.2.0+incompatible

### ISSUE THREAD

**Issue by git136975643** [gofrs/uuid#100]
`go: github.com/gofrs/uuid@v4.2.0+incompatible: Get "https://proxy.golang.org/github.com/gofrs/uuid/@v/v4.2.0+incompatible.mod": dial tcp 142.251.42.241:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

**Comment by cameracker** [comment]
This seems like a network connection issue unique to your set up. Are you behind some company firewall? Are you running into networking issues accessing google's official proxy from your geolocation? 

I'm going to close this issue because this is most likely a networking issue on your side, not a defect with the repository.

Thanks!
