### ISSUE TITLE
Does this produce cryptographically strong uuid values?

### ISSUE THREAD

**Issue by elbek** [gofrs/uuid#105]
Is it possible to generated cryptographically strong uuid values?

**Comment by zerkms** [comment]
v4, v6, and v7 use `crypto/rand` as a source of random data (by default).

**Comment by cameracker** [comment]
Hey @elbek, all of the UUIDs supported in this library are built to specifications according to the corresponding RFCs for each version, but the "cryptographic strength" of the UUID depends on the version in use. v4 is probably the strongest because of its generation algorithm, but it can also be subject to certain classes of brute force replication attacks.

**Comment by elbek** [comment]
Thanks guys, that is great!
