### ISSUE TITLE
Outstanding open issues / PRs in satori/go.uuid

### ISSUE THREAD

**Issue by acln0** [gofrs/uuid#32]
We should take a look at the open issues and pending PRs in https://github.com/satori/go.uuid and see if which ones would be worth tackling / adopting.

https://github.com/satori/go.uuid/pull/44 was brought up, which I think is a good start.

Please comment with other issues or PRs if you think they'd be worth doing.

**Comment by theckman** [comment]
I pinged PR-44 to ask if they'd be willing to re-open the PR here.

**Comment by theckman** [comment]
So here's a quick classification of their issues and PRs:

Desired / In-Progress
- https://github.com/satori/go.uuid/pull/44 (https://github.com/gofrs/uuid/pull/38)
- https://github.com/satori/go.uuid/pull/50 (https://github.com/gofrs/uuid/pull/31)

Fixed by this package:
- https://github.com/satori/go.uuid/pull/72
- https://github.com/satori/go.uuid/pull/75
- https://github.com/satori/go.uuid/pull/85

Obsoleted by this package
- https://github.com/satori/go.uuid/pull/68 (in that we've released a major version)

Unsure if we want to support this:
- https://github.com/satori/go.uuid/pull/63 (Request: https://github.com/satori/go.uuid/issues/64)

**_Issues_**

Feature requests:
- https://github.com/satori/go.uuid/issues/64 (PR: https://github.com/satori/go.uuid/pull/63)
- https://github.com/satori/go.uuid/issues/40

Deprecation requests:
- https://github.com/satori/go.uuid/issues/84
- https://github.com/satori/go.uuid/issues/83

Fixed by this package:
- https://github.com/satori/go.uuid/issues/82
- https://github.com/satori/go.uuid/issues/80
- https://github.com/satori/go.uuid/issues/77
- https://github.com/satori/go.uuid/issues/76
- https://github.com/satori/go.uuid/issues/73
- https://github.com/satori/go.uuid/issues/71
- https://github.com/satori/go.uuid/issues/70
- https://github.com/satori/go.uuid/issues/69
- https://github.com/satori/go.uuid/issues/66

Random questions (should probably be closed):
- https://github.com/satori/go.uuid/issues/81
- https://github.com/satori/go.uuid/issues/79
- https://github.com/satori/go.uuid/issues/78
- https://github.com/satori/go.uuid/issues/74
- https://github.com/satori/go.uuid/issues/47
- https://github.com/satori/go.uuid/issues/38

**Comment by theckman** [comment]
Do we want to support the ability to generate random MAC addresses for V1 IDs as an option? There an issue (64) and PR open (63) on the other repo to support this functionality, and figured I'd poll here before asking.

**Comment by jadr2ddude** [comment]
I think that we should allow the user to specify a MAC address optionally.

**Comment by jadr2ddude** [comment]
I think it makes more sense to allow the user to specify a MAC than to generate a random MAC.

**Comment by zerkms** [comment]
There is a `hwAddrFunc` field available: if we expose it via another constructor - a user may provide a function that returns a random mac every time.

**Comment by theckman** [comment]
We're likely going to need to expose the generator implementation, so that it can be done that way. I think this could be done in a minor release if we wanted, as we'd be adding-on.

**Comment by theckman** [comment]
@zerkms I took a swing based on your comment above: https://github.com/gofrs/uuid/pull/42/files

**Comment by theckman** [comment]
I'm going to close this issue out now, since I think we're engaged on the things we should be engaged on. We can follow those up in the individual PRs/issues.

Thank you for raising this, and for the input that was given by everyone.
