### ISSUE TITLE
Embedding in `NullUUID`

### ISSUE THREAD

**Issue by ricardofandrade** [gofrs/uuid#49]
Is the lack of `UUID` embedding in `NullUUID` by design?
I would expect it to be as close as possible of a drop-in replacement.

**Comment by theckman** [comment]
@ricardofandrade Unfortunately, with us adopting the package I can't say if it was by design. We didn't look to change it, because it seemed okay. The best I can assume is that it was borrowed from other implementations out there, like the MySQL driver and its `NullTime` type:

- https://godoc.org/github.com/go-sql-driver/mysql#NullTime

**Comment by acln0** [comment]
If it were embedded, I think it would be easier for callers to forget that they need to check `Valid` before calling methods. I think having to access a field makes the distinction more obvious, and the distinction is worth making, since method calls would otherwise "work" silently and produce nonsensical results.

**Comment by ricardofandrade** [comment]
@acln0 has a good point: it would be easier to forget and mistakenly to not check `Valid`.

But sometimes that's exactly the goal...
Answering @theckman question: one of the major incentives for me to use `gofrs/uuid` was the enhanced database support (i.e. `NullUUID`) when compared to `google/uuid`.
When I switched between `UUID` to `NullUUID` suddenly I had thousands of places to add `.UUID`.
In my mind the freedom to switch between `UUID` and `NullUUID` should be as cheap as adding/removing `NOT NULL` to my database schema.

That said, I realized with the linked example for MySQL that all other "nullable" `sql` types are built the same way which leads me to the conclusion this is by design and probably due to the concerns mentioned by @acln0 

That said, I don't think any action is needed here. Thanks for your thoughts on this 👍
