### ISSUE TITLE
Add support for providing a custom rand io.Reader

### ISSUE THREAD

**Issue by Willyham** [gofrs/uuid#52]
The current package does not allow me to supply my own `io.Reader` to use in place of the default `rand.Reader`. The use case for this is reproducible tests where I can guarantee the same output by providing a `rand` with a specific seed. Instead, I have to verify in tests that the output of my function is a string in the _form_ of a UUID.

**Comment by jadr2ddude** [comment]
You can actually use the generator interface to make your code testable. You can implement generator and return predefined UUIDs.

**Comment by Willyham** [comment]
Yeah, that's fair. I was already working with an interface which looks like `Generate(*rand.Rand) (string, error)`, and I was trying to avoid the pain of needing to create a few more structs and a separate way of testing for this specific use case.

Happy to do that if this isn't a common request.

**Comment by theckman** [comment]
Sorry for not commenting sooner, was getting caught up on things after being out of town for GopherCon.

My initial thought would be to pass on taking this on as a feature. I definitely appreciate the use case you bring up, but there are a few reasons why I think I'm leaning this way. The first being to reduce the risk of someone introducing flawed UUID generation in to their application. The second is to try to keep the exposed API as small as possible, which makes it easier to iterate on the internals without needing to make breaking API changes.

To @jadr2ddude's point, with there being a (fairly) workable solution for doing this I don't see an absolute need for this being added. That said I'll still mull on it a little bit. I am curious what other @gofrs/all think.

**Comment by leighmcculloch** [comment]
I tend to agree. I can see how adding in that argument would make it testable in that way, but it will muddy the interface of the package which benefits from staying as simple as possible. Using an interface to define what you're depending on to swap it out in tests like it would support making it predictable.

**Comment by dylan-bourque** [comment]
I'm leaning towards agreeing with @jadr2ddude.  The `Generator` interface is compact enough to mock directly.  Also, adding a `NewGenWithReader(r io.Reader)` function solves for tests against `Gen` instances but doesn't help at all with testing code that calls the package-level functions (which all of my usages are doing).  Additionally, would we extend the paradigm to include `NewGenWithHWAFAndReader(hwaf HWAddrFunc, r io.Reader)`?  What about injecting a custom time generator to replace `time.Now()` for `Gen.epochFunc`?

Feels like a slippery slope to address a problem that already has a solution to me.

**Comment by acln0** [comment]
If such a package were to exist, I think it should be named `uuidtest`. Mocking seems like only a singular concern, and we should have a package with a name that leaves it open to extension, rather than restricting its functionality to dealing with mocks.

I think it's reasonably easy to imagine what the proposed `ErrorGenerator` looks like. But what does `PredefinedGenerator` look like? Unfortunately, we have an interface with five methods.

```
type PredefinedGenerator struct {
	V1, V2, V3, V4, V5 uuid.UUID
}
```

looks a bit unwieldy and easy to misuse to me. Callers could do:

```
testUUID := uuid.Must(uuid.NewV4())
g := uuidtest.PredefinedGenerator{
	V4: testUUID,
}
// use g and testUUID together
```

which looks fine, but what does `NewV1()` return, when called on that `g`, if such a (presumably erroneous) call were to happen?

I like the suggestion of lifting the UUID generation into a parameter at the application level -- similarly to what @Xe describes -- much more than providing knobs to turn on generators, or providing mocks/fakes in a separate package, which may or may not be suitable for all use cases.

If someone were to send a PR with a more concrete design and implementation, I think the discussion could be taken further, but, at least for now, I'm not entirely convinced about this.

**Comment by adamdecaf** [comment]
Is one application generating multiple types of UUID's? Why not just make an interface and swap out your deterministic value in tests?

```Go
type uuidgen interface {
   NewV4() (uuid.UUID, error)
}
``` 

I've seen code that increments UUID's (for tests or on-disk data locality). 

The same problem can be solved with time: 

```Go
type clock interface {
   Now() time.Time 
}
```

**Comment by dylan-bourque** [comment]
Agree with @adamdecaf. To me, if you need to mock the generation of uuid values that should be done in your code (by adding a mockable interface as a seam), not by changing the behavior of the library.

**Comment by theckman** [comment]
We've left this open a bit to give an opportunity for more feedback to be shared that would increase the priority for supporting this. I think it feels like it's better to expect consumers to use dependency injection for the UUID generator, than to support replacing the internal `rand.Reader`. We'll close this now, but if at any point feels it's worth looking in to again please file a new issue / link back to this one.
