### ISSUE TITLE
Investigate Codecov as Coveralls replacement

### ISSUE THREAD

**Issue by theckman** [gofrs/uuid#55]
Our coveralls integration hasn't been so consistent when it comes to detecting regressions in code coverage, to the point of being annoying and erroneously failing builds. Let's see whether Codecov can act as a replacement, and if not decide whether we should just rip coveralls out or determine alternate options.

**Comment by theckman** [comment]
Looks like it might be easy: https://github.com/codecov/example-go

**Comment by acln0** [comment]
I am all for this. Coveralls hasn't been very helpful so far.

I am speaking with no in-depth knowledge of how these tools work, but I feel like it would be nice if we could invoke them on demand, on a per-PR basis, instead of having them on all the time. From what I could tell from reading documentation, this doesn't seem possible, but if someone knows something to the contrary, do tell.

In any case, let's try out Codecov and see if it's less noisy and more useful.
